#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AlfaOmega.Resource", IsApplication=true)]

namespace AlfaOmega
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int f100 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int f110 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int f30 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int f40 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int f50 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int f60 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int f70 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int f80 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int f90 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Icon = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050001
			public const int lat = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int lon = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int speedLimit = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int speed_limit = 2131034114;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
